export enum IconType {
  CustomBasket = 'CustomBasket',
  FarCheckCircle = 'FarCheckCircle',
  FarCircle = 'FarCircle',
  FarTimesCircle = 'FarTimesCircle',
  FarTrashAlt = 'FarTrashAlt',
  FasAngleDoubleDown = 'FasAngleDoubleDown',
  FasAngleDoubleUp = 'FasAngleDoubleUp',
  FasArrowCircleLeft = 'FasArrowCircleLeft',
  FasArrowCircleRight = 'FasArrowCircleRight',
  FasArrowLeft = 'FasArrowLeft',
  FasArrowRight = 'FasArrowRight',
  FasChevronDown = 'FasChevronDown',
  FasChevronUp = 'FasChevronUp',
  FasMinus = 'FasMinus',
  FasPercent = 'FasPercent',
  FasPlus = 'FasPlus',
  FasSearch = 'FasSearch',
  FasShoppingBasket = 'FasShoppingBasket'
}
